#!/usr/bin/env python3
"""Rebel Studios' social profiles, written into every page from this one list.

The site has no templating, so the footer is copied into all pages. Edit SOCIAL below and run
    python3 social_links.py
to rewrite the block between the social:start/social:end markers in every footer, and the
Organization "sameAs" list that tells search engines these profiles belong to the studio.
Accounts were checked to exist on 2026-09-17.
"""
import json
import pathlib
import re

SOCIAL = [
    ("X", "https://x.com/RStudios64042"),
    ("Bluesky", "https://bsky.app/profile/rebelstudios.bsky.social"),
    ("Farcaster", "https://farcaster.xyz/rebelstudios"),
    ("Zora", "https://zora.co/@rebelstudios"),
    ("GitHub", "https://github.com/pgalyen1987"),
    ("LinkedIn", "https://www.linkedin.com/in/patrick-galyen-5410b9a7/"),
    ("Gumroad", "https://rebelstudios.gumroad.com"),
]

ROOT = pathlib.Path(__file__).resolve().parent
BLOCK_RE = re.compile(r"[ \t]*<!-- social:start.*?<!-- social:end -->\n?", re.S)
COPY_RE = re.compile(r'([ \t]*)<p class="footer-copy">')


def block(indent: str) -> str:
    links = "\n".join(
        f'{indent}    <a href="{url}" target="_blank" rel="me noopener noreferrer">{name}</a>'
        for name, url in SOCIAL
    )
    return (
        f"{indent}<!-- social:start (generated by social_links.py; edit the list there) -->\n"
        f'{indent}<nav class="footer-social" aria-label="Rebel Studios elsewhere">\n'
        f"{links}\n"
        f"{indent}</nav>\n"
        f"{indent}<!-- social:end -->\n"
    )


def main() -> None:
    pages = sorted(ROOT.glob("*.html")) + sorted(ROOT.glob("tools/*.html"))
    changed, missing = [], []
    for page in pages:
        html = page.read_text(encoding="utf-8")
        new = BLOCK_RE.sub("", html)
        footer_at = new.find('<footer class="footer">')
        copy = COPY_RE.search(new, footer_at) if footer_at >= 0 else None
        if not copy:
            missing.append(page.name)
            continue
        new = new[: copy.start()] + block(copy.group(1)) + new[copy.start():]
        new = re.sub(
            r'"sameAs":\s*\[[^\]]*\]',
            '"sameAs":' + json.dumps([url for _, url in SOCIAL], separators=(",", ":")),
            new,
        )
        if new != html:
            page.write_text(new, encoding="utf-8")
            changed.append(page.name)
    print(f"{len(pages)} pages, {len(changed)} updated")
    if missing:
        print("no standard footer (not changed):", ", ".join(missing))


if __name__ == "__main__":
    main()
